export const skills = [
  [100, "React", "React.svg"],
  [100, "Tailwind", "tailwind.svg"],
  [95, "Next", "next.svg"],
  [90, "Node", "node.svg"],
  [90, "Express", "express.svg"],
  [70, "Java", "Java.svg"],
  [100, "HTML", "Html.svg"],
  [100, "CSS", "Css.svg"],
  [100, "Javascript", "Javascript.svg"],
  [70, "PHP", "PHP.svg"],
  [70, "MySQL", "MySQL.svg"],
  [60, "C++", "C++.svg"],
  [70, "Symfony", "Symfony.svg"],
  [50, "Python", "Python.svg"],
  [70, "Angular", "Python.svg"],
  [70, ".NET", "dotnet.svg"],
  [60, "Django", "django.svg"],
  [40, "Rust", "rust.svg"],
  [10, "Solidity", "solidity.svg"],
];
